[phases.setup]
nixPkgs = ["python310", "gcc", "zlib"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmds = ["bash start_cloud.sh"]

